image:
  repository: postgres
  tag: latest
  pullPolicy: IfNotPresent

restartPolicy: Never

service:
  port1: 5433
persistence:
  name:database-volume
  mountPath:/var/lib/postgresql
  enabled: true
