apiVersion: v1
kind: Pod
metadata:
  name: pi-app
 
spec:
  containers:
  - image: postgres
    imagePullPolicy: IfNotPresent
    name: waiter
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: default-volume
      readOnly: false
  
  volumes:
  - name: default-volume
 
