apiVersion: v1
kind: Pod
metadata:
  name: pi-app
 
spec:
  initContainers:
  - image: postgres
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: default-volume
      readOnly: false
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123" 
   
  - image: kpi-image
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: default-volume
      readOnly: false
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123"    
    
  volumes:
  - name: default-volume
 
