apiVersion: v1
kind: Pod
metadata:
  name: pi-app
 
spec:
  containers:
  - image: postgres
    imagePullPolicy: IfNotPresent
    name: waiter
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: default-volume
      readOnly: false
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123" 
    ports:
    - containerPort:5433 
    
  - image: kpi-image
    imagePullPolicy: IfNotPresent
    name: waiter
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: default-volume
      readOnly: false
    env:
    - name: "POSTGRES_DB"
      value: "postgres"
    - name: "POSTGRES_USER"
      value: "postgres"
    - name: "POSTGRES_PASSWORD"
      value: "Siemens123"    
    ports:
    - containerPort: 4502
  volumes:
  - name: default-volume
 
