apiVersion: extensions/v1beta1
kind: Pod
metadata:
  name: alpine-nmcvj-alpine
spec:
  containers:
  - image: postgres
    imagePullPolicy: IfNotPresent
    name: waiter
    volumeMounts:
    - mountPath: /var/lib/postgresql
      name: default-volume
      readOnly: false
  
  volumes:
  - name: default-volume
    
